#pragma once

#include "cut/preprocessor/stringize.h"

#define CUT_VERSION_RELEASE 0
#define CUT_VERSION_MAJOR 2
#define CUT_VERSION_MINOR 0

#define CUT_VERSION ((CUT_VERSION_RELEASE << 16) | (CUT_VERSION_MAJOR << 8) | CUT_VERSION_MINOR)

#define CUT_VERSION_STRING "cut v" CUT_STRINGIZE(CUT_VERSION_RELEASE) "." CUT_STRINGIZE(CUT_VERSION_MAJOR) "." CUT_STRINGIZE(CUT_VERSION_MINOR) ""
